### ISSUE TITLE
Failing to install Python 3.7 on macOS arm64

### ISSUE THREAD

**Issue by krlmlr** [duckdb/extension-ci-tools#13]
https://github.com/hannes/duckdb-rfuns/actions/runs/8816067894/job/24199401883#step:5:17

```
  Version 3.7 was not found in the local cache
  Error: The version '3.7' with architecture 'arm64' was not found for macOS 14.4.1.
  The list of all available versions can be found here: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
```

Interestingly, the same error appears on macOS amd64, even if Python 3.7 seems to be supported there: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json

https://github.com/hannes/duckdb-rfuns/actions/runs/8816067894/job/24199401199#step:5:17

Is there any downside to bumping to the most recent version?

**Comment by krlmlr** [comment]
Why do we even need to install Python? Is the regular `python3` available on the workers not sufficient here? Seems to be sufficient for the "deploy" workflows.

**Comment by krlmlr** [comment]
I have no idea why duckdb_spatial seems to work. Caching?

https://github.com/duckdb/duckdb_spatial/actions/runs/8680419083/job/23800921790

**Comment by carlopi** [comment]
I think this can be closed, there are still some variance in Python version used but it should be OK for now since the lowest is 3.9.
