### ISSUE TITLE
Add/Define additional Build-Time dependencies

### ISSUE THREAD

**Issue by hafenkran** [duckdb/extension-ci-tools#55]
I'm currently in the process of preparing an extension for inclusion in the community extension repo. However, the compilation of this extension requires some additional build-time dependencies that are not included in the shared build workflow. Specifically, the following packages are needed: `bison`, `flex`, `pkg-config`, and `libcurl`. 

These dependencies are essential for the compilation of the extension and, I guess, these dependencies are also quite common for other potential DuckDB extensions. For reference, you can also compare the necessary dependencies listed in my workflow file [here](https://github.com/hafenkran/duckdb-bigquery/blob/d9b229d14de79701f0e16f873375126b78cb5711/.github/workflows/_extension_distribution.yml#L159).

Would it be possible to integrate these dependencies into the workflow, or alternatively, to define them as additional optional dependencies within the community extensions repo? I don't know the process you currently prefer. 

Many thanks in advance!

**Comment by samansmink** [comment]
Hey @hafenkran I'm happy to add dependencies to the default toolchain. I have a question though: regarding `libcurl`, what's the reason you want this installed through the OS? I see you already use vcpkg to install it, doesn't that work?

**Comment by hafenkran** [comment]
Unfortunately not. It only worked out for windows featured by schannel. I faced certificate verification errors on certain builds, which is why all tests kept failing. I spent quite some time figuring out why, but the only solution that helped was using the pre installed one.

**Comment by samansmink** [comment]
I have https://github.com/duckdb/extension-ci-tools/pull/56 open which add bison, flex and sneaks in the missing pkgconfig.

For libcurl I would really like to put in some effort to get it to work with the vcpkg based one. I could help out a little there. Do you have any logs with errors for me?

**Comment by algosday** [comment]
Looks like I also need `autoconf` for my setup.
https://github.com/algosday/duckdb-journald/actions/runs/10228995987/job/28302135345#step:18:104

Also, it might be a good idea to have a workflow input for extra dependencies. This would be useful because not all dependencies are universally needed across different extensions. ( I also need `libsystemd-dev` for this extension, which is only relevant to this context.  )

**Comment by hafenkran** [comment]
Sorry @samansmink, I was super busy this week and only got to it today. Thanks for adding those!

Miraculously, I managed to get it working yesterday without the libcurl OS install. I have no idea why, but it’s working now, possibly due to some package updates in the past. I remember spending quite a bit of time on it back then (especially on gcc4).

But I totally agree: having a mechanism to handle extra dependencies in the workflow would be really nice for the future.

**Comment by hafenkran** [comment]
I found a workaround. It seems like libcurl isn't required anymore. Thanks!
