### ISSUE TITLE
Extension deployment failing due to deprecation of actions/download-artifact: v2

### ISSUE THREAD

**Issue by Dtenwolde** [duckdb/extension-ci-tools#68]
Hi there, 
With the latest update to v1.1.0, I noticed that during the extension deployment phase, all actions are failing with the following error: 

Error: This request has been automatically failed because it uses a deprecated version of `actions/download-artifact: v2`. Learn more: https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/

See [failing action here](https://github.com/cwida/duckpgq-extension/actions/runs/10789366851/job/29924688389)

I see that the H3 extension managed to deploy successfully, see [here](https://github.com/isaacbrodsky/h3-duckdb/actions/runs/10775683621/job/29882027236). So maybe it is something on my end.

**Comment by carlopi** [comment]
Time travel: https://github.com/duckdb/extension-ci-tools/pull/67

**Comment by carlopi** [comment]
Thanks for raising this, it want to double check for CI, I would assume merging in 30' or so

**Comment by Dtenwolde** [comment]
Thanks for the quick reply, I'll wait for the CI and rerun mine 👍

**Comment by carlopi** [comment]
Should be up, can you give it a try?

**Comment by Dtenwolde** [comment]
Running, see status here https://github.com/cwida/duckpgq-extension/actions/runs/10791924141

**Comment by Dtenwolde** [comment]
Run failed: https://github.com/cwida/duckpgq-extension/actions/runs/10791924141/workflow 
But I think the issue was not in the extension-ci-tools but in `.github/workflows/_extension_deploy.yml` --> https://github.com/cwida/duckpgq-extension/commit/93a49ea95b45bd67f5467a4f8846491399d94d67

Maybe that's why other extensions had no trouble
Either way this issue can stay closed :) Thanks
